In [1]:
import numpy as np

In [25]:
# particle data struction np.array([posX, posY, posZ, velX, velY, velZ, i, j, k, typeID])
class test:
    def __init__(self, parcel):
        self.parcel = parcel

    def boundary(self):
        cellSizeX = 10
        cellSizeY = 10
        cellSizeZ = 10
        symmetry = True
        celllength = 1

        if symmetry == True:
            indiceXMax = self.parcel[:, 6] >= cellSizeX
            indiceXMin = self.parcel[:, 6] < 0

            # 使用布尔索引进行调整
            self.parcel[indiceXMax, 6] -= cellSizeX
            self.parcel[indiceXMax, 0] -= celllength * cellSizeX

            self.parcel[indiceXMin, 6] += cellSizeX
            self.parcel[indiceXMin, 0] += celllength * cellSizeX

            # 检查并调整 j_cp 和对应的 pos_cp
            indiceYMax = self.parcel[:, 7] >= cellSizeY
            indiceYMin = self.parcel[:, 7] < 0

            # 使用布尔索引进行调整
            self.parcel[indiceYMax, 7] -= cellSizeY
            self.parcel[indiceYMax, 1] -= celllength * cellSizeY

            self.parcel[indiceYMin, 7] += cellSizeY
            self.parcel[indiceYMin, 1] += celllength * cellSizeY
        
        indices = np.logical_or(self.parcel[:, 6] >= cellSizeX, self.parcel[:, 6] < 0)
        indices |= np.logical_or(self.parcel[:, 7] >= cellSizeY, self.parcel[:, 7] < 0)
        indices |= np.logical_or(self.parcel[:, 8] >= cellSizeZ, self.parcel[:, 8] < 0)

        if np.any(indices):
            self.parcel = self.parcel[~indices]

    def run(self):
        self.boundary()


In [26]:
partcell = np.arange(45).reshape((5, 9))
partcell[1, 8] = 8
print(partcell)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16  8]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]]


In [27]:
test2 = test(partcell)

In [28]:
test2.run()
print(test2.parcel)

[[ 0  1  2  3  4  5  6  7  8]
 [-1  0 11 12 13 14  5  6  8]]
