In [1]:
import numpy as np

In [2]:
# particle data struction np.array([posX, posY, posZ, velX, velY, velZ, i, j, k, typeID])
def boundary(parcel):
    cellSizeX = 10
    cellSizeY = 10
    cellSizeZ = 10
    symmetry = True
    celllength = 1

    if symmetry == True:
        indiceXMax = parcel[:, 6] >= cellSizeX
        indiceXMin = parcel[:, 6] < 0

        # 使用布尔索引进行调整
        parcel[indiceXMax, 6] -= cellSizeX
        parcel[indiceXMax, 0] -= celllength * cellSizeX

        parcel[indiceXMin, 6] += cellSizeX
        parcel[indiceXMin, 0] += celllength * cellSizeX

        # 检查并调整 j_cp 和对应的 pos_cp
        indiceYMax = parcel[:, 7] >= cellSizeY
        indiceYMin = parcel[:, 7] < 0

        # 使用布尔索引进行调整
        parcel[indiceYMax, 7] -= cellSizeY
        parcel[indiceYMax, 1] -= celllength * cellSizeY

        parcel[indiceYMin, 7] += cellSizeY
        parcel[indiceYMin, 1] += celllength * cellSizeY
    
    indices = np.logical_or(parcel[:, 6] >= cellSizeX, parcel[:, 6] < 0)
    indices |= np.logical_or(parcel[:, 7] >= cellSizeY, parcel[:, 7] < 0)
    indices |= np.logical_or(parcel[:, 8] >= cellSizeZ, parcel[:, 8] < 0)

    if np.any(indices):
        parcel = parcel[~indices]

    return parcel

In [6]:
partcell = np.arange(45).reshape((5, 9))
partcell[1, 8] = 8
print(partcell)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16  8]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]]


In [7]:
print(boundary(partcell))

[[ 0  1  2  3  4  5  6  7  8]
 [-1  0 11 12 13 14  5  6  8]]
