In [1]:
import numpy as np
import time as Time
from numba import jit
import matplotlib.pyplot as plt
import pyvista as pv
import torch

In [2]:
film = np.zeros((100, 100, 200, 2))

bottom = 100
height = 140

density = 10

sphere = np.ones((100, 100, 200), dtype=bool)

radius = 30

center = 50
for i in range(sphere.shape[0]):
    for j in range(sphere.shape[1]):
        if np.abs(i-center)*np.abs(i-center) + np.abs(j-center)*np.abs(j-center) < radius*radius:
            sphere[i, j, bottom:height] = 0

film[sphere, 1] = density
film[:, :, height:, :] = 0
film[:, :, 0:bottom, 0] = density # bottom
film[:, :, 0:bottom, 1] = 0 # bottom
# film[:, :30, bottom:height, 1] = 10
# film[:, -30:, bottom:height, 1] = 10


In [3]:
sumFilm = np.sum(film, axis=-1)

print(sumFilm.shape)

(100, 100, 200)


In [3]:
depo1 = torch.Tensor(film[:, 50:, :, 1]!=0).to_sparse()
depo1 = depo1.indices().numpy().T

substrute = torch.Tensor(film[:, 50:, :,0]!=0).to_sparse()
substrute = substrute.indices().numpy().T
depomesh = pv.PolyData(depo1)
depomesh["radius"] = np.ones(depo1.shape[0])*0.5
geom = pv.Box()

submesh = pv.PolyData(substrute)
submesh["radius"] = np.ones(substrute.shape[0])*0.5

# Progress bar is a new feature on master branch
depoglyphed = depomesh.glyph(scale="radius", geom=geom) # progress_bar=True)
subglyphed = submesh.glyph(scale="radius", geom=geom) # progress_bar=True)

p = pv.Plotter()
p.add_mesh(depoglyphed, color='cyan')
p.add_mesh(subglyphed, color='dimgray')
p.enable_eye_dome_lighting()
p.show()

c:\Users\urcs049\AppData\Local\anaconda3\Lib\site-packages\pyvista\core\utilities\points.py:55: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(
c:\Users\urcs049\AppData\Local\anaconda3\Lib\site-packages\pyvista\core\filters\data_set.py:2386: UserWarning: No vector-like data to use for orient. orient will be set to False.
  warnings.warn("No vector-like data to use for orient. orient will be set to False.")


Widget(value='<iframe src="http://localhost:63146/index.html?ui=P_0x23864db1610_0&reconnect=auto" class="pyvis…

In [8]:
etchfilm = film

In [3]:
etchfilm = np.load('bosch_sf_step2.npy')

In [58]:
indice_c4 = etchfilm[:, :, :, 1] >= 10
etchfilm[indice_c4, 1] = 10

In [5]:
depo1 = torch.Tensor(etchfilm[:50, :, :, 1]!=0).to_sparse()
depo1 = depo1.indices().numpy().T

substrute = torch.Tensor(etchfilm[:50, :, :,0]!=0).to_sparse()
substrute = substrute.indices().numpy().T
depomesh = pv.PolyData(depo1)
depomesh["radius"] = np.ones(depo1.shape[0])*0.5
geom = pv.Box()

submesh = pv.PolyData(substrute)
submesh["radius"] = np.ones(substrute.shape[0])*0.5

# Progress bar is a new feature on master branch
depoglyphed = depomesh.glyph(scale="radius", geom=geom) # progress_bar=True)
subglyphed = submesh.glyph(scale="radius", geom=geom) # progress_bar=True)

p = pv.Plotter()
p.add_mesh(depoglyphed, color='cyan')
p.add_mesh(subglyphed, color='dimgray')
p.enable_eye_dome_lighting()
p.show()

c:\Users\urcs049\AppData\Local\anaconda3\Lib\site-packages\pyvista\core\utilities\points.py:55: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(
c:\Users\urcs049\AppData\Local\anaconda3\Lib\site-packages\pyvista\core\filters\data_set.py:2386: UserWarning: No vector-like data to use for orient. orient will be set to False.
  warnings.warn("No vector-like data to use for orient. orient will be set to False.")


Widget(value='<iframe src="http://localhost:63129/index.html?ui=P_0x1fa5759af00_0&reconnect=auto" class="pyvis…

In [62]:
etchfilm[50, 55, 45:]

array([[10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [ 0., 10.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,

In [5]:
import Multi_Species_bosch_etching

In [6]:
def max_velocity_u( random1, random2):
    return np.sqrt(-np.log(random1))*(np.cos(2*np.pi*random2))

def max_velocity_w( random1, random2):
    return np.sqrt(-np.log(random1))*(np.sin(2*np.pi*random2))

def max_velocity_v( random3):
    return -np.sqrt(-np.log(random3))

In [68]:
# F+ Ar+ 

N = int(5e7)
velosity_matrix = np.zeros((N, 3))
# tstep=1e-5
# celllength=1e-5
# velosity_matrix[:, 0] = -1 * celllength /tstep
# velosity_matrix[:, 1] = -1 * celllength /tstep
Random1 = np.random.rand(N)
Random2 = np.random.rand(N)
Random3 = np.random.rand(N)
velosity_matrix = np.array([max_velocity_u(Random1, Random2), \
                            max_velocity_w(Random1, Random2), \
                                max_velocity_v(Random3)]).T

energy = np.linalg.norm(velosity_matrix, axis=1)
velosity_matrix[:,0] = np.divide(velosity_matrix[:,0], energy)
velosity_matrix[:,1] = np.divide(velosity_matrix[:,1], energy)
velosity_matrix[:,2] = np.divide(velosity_matrix[:,2], energy)

# velosity_matrix[:, 2] = -1 * celllength /tstep

typeID = np.zeros(N)
# FO_ratio = int(N/4)
# typeID[-FO_ratio:] = 1

# add Ar+
# ion_ration = int(N/4)
# typeID[-ion_ration:] = 2
# velosity_matrix[-ion_ration:, 0] = np.random.rand(ion_ration)*0.01 - 0.005
# velosity_matrix[-ion_ration:, 1] = np.random.rand(ion_ration)*0.01 - 0.005
# velosity_matrix[-ion_ration:, 2] = -1 
# add Ar+


vel_type_shuffle = np.zeros((N, 4))
vel_type_shuffle[:, :3] = velosity_matrix
vel_type_shuffle[:, -1] = typeID

np.random.shuffle(vel_type_shuffle)
# print(typeID[:10])
# print(velosity_matrix[0])
print(vel_type_shuffle[:10])

[[-0.92889783  0.15931923 -0.33431453  0.        ]
 [ 0.78779109 -0.38683857 -0.47931317  0.        ]
 [-0.15858218  0.51476667 -0.84253603  0.        ]
 [-0.19781371  0.9483352  -0.24805259  0.        ]
 [ 0.92424542  0.31607501 -0.2141658   0.        ]
 [-0.29489356  0.16342153 -0.94145164  0.        ]
 [ 0.69853796  0.64166433 -0.31672008  0.        ]
 [ 0.49317709  0.51804704 -0.6988588   0.        ]
 [ 0.30306805 -0.62438694 -0.71992409  0.        ]
 [ 0.81990249  0.06932581 -0.56829028  0.        ]]


In [63]:
N = int(1e6)
velosity_matrix = np.zeros((N, 3))

typeID = np.zeros(N)
# FO_ratio = int(N/4)
# typeID[-FO_ratio:] = 1

ion_ration = int(N)
typeID[-ion_ration:] = 2
velosity_matrix[-ion_ration:, 0] = np.random.rand(ion_ration)*0.01 - 0.005
velosity_matrix[-ion_ration:, 1] = np.random.rand(ion_ration)*0.01 - 0.005
velosity_matrix[-ion_ration:, 2] = -1 

vel_type_shuffle = np.zeros((N, 4))
vel_type_shuffle[:, :3] = velosity_matrix
vel_type_shuffle[:, -1] = typeID

np.random.shuffle(vel_type_shuffle)
# print(typeID[:10])
# print(velosity_matrix[0])
print(vel_type_shuffle[:10])

[[ 5.40091043e-04  3.14177961e-03 -1.00000000e+00  2.00000000e+00]
 [-4.54078428e-03  2.57382055e-03 -1.00000000e+00  2.00000000e+00]
 [ 3.77557195e-03  3.94541595e-03 -1.00000000e+00  2.00000000e+00]
 [ 4.05191839e-03  1.63245413e-03 -1.00000000e+00  2.00000000e+00]
 [-2.26384230e-03 -3.41551823e-03 -1.00000000e+00  2.00000000e+00]
 [-2.50544706e-04  4.96622775e-04 -1.00000000e+00  2.00000000e+00]
 [ 2.16436864e-03  3.45842638e-03 -1.00000000e+00  2.00000000e+00]
 [ 1.74127788e-03  2.16614901e-03 -1.00000000e+00  2.00000000e+00]
 [ 2.57891242e-03 -2.19787644e-03 -1.00000000e+00  2.00000000e+00]
 [-3.60594991e-03 -2.53308143e-03 -1.00000000e+00  2.00000000e+00]]


In [14]:
print(vel_type_shuffle[10:20])

[[-3.68380774e-01  5.11607868e-01 -7.76242872e-01  0.00000000e+00]
 [-2.62083917e-01 -8.45568133e-01 -4.65109183e-01  0.00000000e+00]
 [-5.65620406e-01  3.02950370e-01 -7.67003670e-01  0.00000000e+00]
 [-6.15339422e-02 -4.23597030e-01 -9.03758336e-01  0.00000000e+00]
 [-4.84750871e-01  1.73537876e-01 -8.57263786e-01  0.00000000e+00]
 [-2.14957732e-01  5.32181143e-01 -8.18887297e-01  0.00000000e+00]
 [-3.23637043e-01 -7.59884259e-01 -5.63768550e-01  0.00000000e+00]
 [-4.28698360e-01 -1.71049598e-01 -8.87107520e-01  0.00000000e+00]
 [ 8.46669637e-04  4.75093596e-04 -1.00000000e+00  2.00000000e+00]
 [-5.71897263e-01  4.47035248e-01 -6.87817568e-01  0.00000000e+00]]


In [49]:
# c4f8

N = int(1e7)
velosity_matrix = np.zeros((N, 3))
# tstep=1e-5
# celllength=1e-5
# velosity_matrix[:, 0] = -1 * celllength /tstep
# velosity_matrix[:, 1] = -1 * celllength /tstep
Random1 = np.random.rand(N)
Random2 = np.random.rand(N)
Random3 = np.random.rand(N)
velosity_matrix = np.array([max_velocity_u(Random1, Random2), \
                            max_velocity_w(Random1, Random2), \
                                max_velocity_v(Random3)]).T

energy = np.linalg.norm(velosity_matrix, axis=1)
velosity_matrix[:,0] = np.divide(velosity_matrix[:,0], energy)
velosity_matrix[:,1] = np.divide(velosity_matrix[:,1], energy)
velosity_matrix[:,2] = np.divide(velosity_matrix[:,2], energy)

# velosity_matrix[:, 2] = -1 * celllength /tstep

typeID = np.ones(N)
# FO_ratio = int(N/4)
# typeID[-FO_ratio:] = 1

# ion_ration = int(N/8)
# typeID[-ion_ration:] = 2
# velosity_matrix[-ion_ration:, 0] = np.random.rand(ion_ration)*0.001
# velosity_matrix[-ion_ration:, 1] = np.random.rand(ion_ration)*0.001
# velosity_matrix[-ion_ration:, 2] = -1 

vel_type_shuffle = np.zeros((N, 4))
vel_type_shuffle[:, :3] = velosity_matrix
vel_type_shuffle[:, -1] = typeID

np.random.shuffle(vel_type_shuffle)
# print(typeID[:10])
# print(velosity_matrix[0])
print(vel_type_shuffle[:10])

[[-0.17839113 -0.86820551 -0.46302894  1.        ]
 [ 0.41936594  0.45306316 -0.78668036  1.        ]
 [ 0.68916596 -0.47394099 -0.54811516  1.        ]
 [-0.64269414 -0.07646823 -0.76229709  1.        ]
 [-0.76288849 -0.25496899 -0.59413127  1.        ]
 [-0.69749417  0.50898933 -0.50441228  1.        ]
 [ 0.17935686  0.28565881 -0.94139798  1.        ]
 [ 0.15481802  0.45571212 -0.87656023  1.        ]
 [ 0.5249166  -0.56691386 -0.63487891  1.        ]
 [ 0.28321522  0.69085135 -0.66521692  1.        ]]


In [69]:
#etching
logname = 'Multi_species_bosch_911'
testEtch = Multi_Species_bosch_etching.etching(mirror=True,inputMethod='bunch', depo_or_etching='etching', 
                            etchingPoint = np.array([center, center, 37]),depoPoint = np.array([center, center, 37]),
                            density=density, center_with_direction=np.array([[35,100,75]]), 
                            range3D=np.array([[0, 70, 0, 100, 0, 150]]), InOrOut=[1], yield_hist=np.array([None]),
                            reaction_type=False, param = [1.6, -0.7], N = N, 
                            sub_xy=[0,0], film=etchfilm, n=1, cellSize=etchfilm.shape, 
                            celllength=1e-5, kdtreeN=5, tstep=1e-5,
                            substrateTop=80,posGeneratorType='top', logname=logname)


# etching = testEtch.depo_position_increase_cosVel_normal(125, int(7e6), 2e-3, 5)


In [52]:
#depo
logname = 'Multi_species_bosch_911'
testEtch = Multi_Species_bosch_etching.etching(mirror=True,inputMethod='bunch', depo_or_etching='depo', 
                            etchingPoint = np.array([center, center, 45]),depoPoint = np.array([center, center, 45]),
                            density=density, center_with_direction=np.array([[35,100,75]]), 
                            range3D=np.array([[0, 70, 0, 100, 0, 150]]), InOrOut=[1], yield_hist=np.array([None]),
                            reaction_type=False, param = [1.6, -0.7], N = N, 
                            sub_xy=[0,0], film=etchfilm, n=1, cellSize=etchfilm.shape, 
                            celllength=1e-5, kdtreeN=5, tstep=1e-5,
                            substrateTop=80,posGeneratorType='top', logname=logname)

In [70]:
etching = testEtch.inputParticle(125,vel_type_shuffle[:,:3], vel_type_shuffle[:,-1], 2e-2, 5)

running:  37%|███████████████████▌                                 | 37.0/100 [22:29<43:04, 41.0s/B]

In [67]:
np.save('bosch_sf_step9', etchfilm)

In [47]:
etchfilm[50, 50, 60:]

array([[10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [ 0.,  6.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,

In [13]:
etchfilm[50, 50, 60:]

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [43]:
etching[0][50, 50, 60:]

array([[10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [10.,  0.],
       [ 0., 10.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,

In [19]:
depo1 = torch.Tensor(etching[0][:, 50:, :, 1]!=0).to_sparse()
depo1 = depo1.indices().numpy().T

substrute = torch.Tensor(etching[0][:, 50:, :,0]!=0).to_sparse()
substrute = substrute.indices().numpy().T
depomesh = pv.PolyData(depo1)
depomesh["radius"] = np.ones(depo1.shape[0])*0.5
geom = pv.Box()

submesh = pv.PolyData(substrute)
submesh["radius"] = np.ones(substrute.shape[0])*0.5

# Progress bar is a new feature on master branch
depoglyphed = depomesh.glyph(scale="radius", geom=geom) # progress_bar=True)
subglyphed = submesh.glyph(scale="radius", geom=geom) # progress_bar=True)

p = pv.Plotter()
p.add_mesh(depoglyphed, color='cyan')
p.add_mesh(subglyphed, color='dimgray')
p.enable_eye_dome_lighting()
p.show()

c:\Users\urcs049\AppData\Local\anaconda3\Lib\site-packages\pyvista\core\utilities\points.py:55: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(
c:\Users\urcs049\AppData\Local\anaconda3\Lib\site-packages\pyvista\core\filters\data_set.py:2386: UserWarning: No vector-like data to use for orient. orient will be set to False.
  warnings.warn("No vector-like data to use for orient. orient will be set to False.")


Widget(value='<iframe src="http://localhost:63391/index.html?ui=P_0x15f0e8c6bd0_2&reconnect=auto" class="pyvis…

In [66]:
depo1 = torch.Tensor(etchfilm[:50, :, :, 1]!=0).to_sparse()
depo1 = depo1.indices().numpy().T

substrute = torch.Tensor(etchfilm[:50, :, :,0]!=0).to_sparse()
substrute = substrute.indices().numpy().T
depomesh = pv.PolyData(depo1)
depomesh["radius"] = np.ones(depo1.shape[0])*0.5
geom = pv.Box()

submesh = pv.PolyData(substrute)
submesh["radius"] = np.ones(substrute.shape[0])*0.5

# Progress bar is a new feature on master branch
depoglyphed = depomesh.glyph(scale="radius", geom=geom) # progress_bar=True)
subglyphed = submesh.glyph(scale="radius", geom=geom) # progress_bar=True)

p = pv.Plotter()
p.add_mesh(depoglyphed, color='cyan')
p.add_mesh(subglyphed, color='dimgray')
p.enable_eye_dome_lighting()
p.show()

c:\Users\urcs049\AppData\Local\anaconda3\Lib\site-packages\pyvista\core\utilities\points.py:55: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(
c:\Users\urcs049\AppData\Local\anaconda3\Lib\site-packages\pyvista\core\filters\data_set.py:2386: UserWarning: No vector-like data to use for orient. orient will be set to False.
  warnings.warn("No vector-like data to use for orient. orient will be set to False.")


Widget(value='<iframe src="http://localhost:63391/index.html?ui=P_0x15f92cd3020_8&reconnect=auto" class="pyvis…