In [1]:
from numba import jit
import numpy as np
import time
import timeit

In [29]:
class CalculatorOriginal:
    def __init__(self, data):
        self.data = data

    def complex_calculation(self):
        result = np.zeros_like(self.data)
        for i in range(self.data.shape[0]):
            for j in range(self.data.shape[1]):
                result[i, j] = self.data[i, j] ** 2 + self.data[i, j] ** 0.5
        self.data = result

# -----------------------------------------

# @jit(nopython=True)
def accelerated_calculation(data):
    result = np.zeros_like(data)
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            result[i, j] = data[i, j] ** 2 + data[i, j] ** 0.5
    return result


class CalculatorNumba:
    def __init__(self, data):
        self.data = data

    def complex_calculation(self):
        self.data = accelerated_calculation(self.data)

# ------------------------------------------

if __name__ == "__main__":
    data = np.random.rand(1000, 1000)
    
    # 测试原始计算的时间
    calc_original = CalculatorOriginal(data)
    original_time = timeit.timeit(lambda: calc_original.complex_calculation(), number=10)
    print(f"Original time: {original_time:.6f} seconds")

    # 测试使用 Numba 加速后的计算时间
    calc_numba = CalculatorNumba(data)
    # 预编译 JIT 函数
    calc_numba.complex_calculation()
    numba_time = timeit.timeit(lambda: calc_numba.complex_calculation(), number=10)
    print(f"Numba time: {numba_time:.6f} seconds")


Original time: 7.910119 seconds


C:\Users\URCS049\AppData\Local\Temp\ipykernel_25320\582554447.py:19: RuntimeWarning: overflow encountered in scalar power
  result[i, j] = data[i, j] ** 2 + data[i, j] ** 0.5


Numba time: 8.217910 seconds


In [22]:
class CalculatorOriginal:
    def __init__(self, data):
        self.data = data

    def complex_calculation(self):
        result = np.zeros_like(self.data)
        for i in range(self.data.shape[0]):
            for j in range(self.data.shape[1]):
                result[i, j] = self.data[i, j] ** 2 + self.data[i, j] ** 0.5
        self.data = result
    
data = np.random.rand(1000, 1000)
print(data)
calc_test = CalculatorOriginal(data)

calc_test.complex_calculation()

print(calc_test.data)

[[0.49600595 0.93845428 0.67427997 ... 0.92974211 0.77377456 0.59132995]
 [0.73673203 0.45491564 0.90079759 ... 0.48826791 0.38112829 0.08280017]
 [0.35565839 0.36445795 0.32208784 ... 0.24490739 0.48128493 0.40338843]
 ...
 [0.78058735 0.83822773 0.95321117 ... 0.10289345 0.46654866 0.43741672]
 [0.02174867 0.06566292 0.47144549 ... 0.18416633 0.51289828 0.00516904]
 [0.1974296  0.41479221 0.83625938 ... 0.47119455 0.99842886 0.47629849]]
[[0.95029879 1.84943493 1.27579899 ... 1.82865174 1.47837164 1.11865092]
 [1.40110505 0.88142258 1.76053987 ... 0.93716725 0.76261465 0.29460605]
 [0.72286391 0.73653313 0.67126841 ... 0.55486082 0.92538221 0.79785089]
 ...
 [1.49282516 1.6181735  1.88493686 ... 0.33135716 0.90071132 0.85270825]
 [0.14794729 0.26055938 0.90887972 ... 0.46306328 0.97923382 0.07192276]
 [0.48330896 0.81609622 1.61380194 ... 0.90846043 1.99607431 0.91700406]]


In [28]:
# @jit(nopython=True)
def accelerated_calculation(data):
    result = np.zeros_like(data)
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            result[i, j] = data[i, j] ** 2 + data[i, j] ** 0.5
    return result


class CalculatorNumba:
    def __init__(self, data):
        self.data = data

    def complex_calculation(self):
        self.data = accelerated_calculation(self.data)
    

data = np.random.rand(1000, 1000)
print(data)
calc_numba = CalculatorNumba(data)
calc_numba.complex_calculation()
print(calc_numba.data)


[[0.3481128  0.22401601 0.89867827 ... 0.06410288 0.80008317 0.39460969]
 [0.20401002 0.94399547 0.64140701 ... 0.33866375 0.1658476  0.37811758]
 [0.42334751 0.98716634 0.60013323 ... 0.61540784 0.39354528 0.78173449]
 ...
 [0.63614205 0.05211516 0.91310775 ... 0.51643384 0.72436372 0.98040531]
 [0.2765018  0.55115241 0.45819389 ... 0.85824487 0.4893406  0.03324239]
 [0.99200591 0.3397119  0.10288137 ... 0.59271878 0.25298864 0.83874021]]
[[0.71119337 0.52348647 1.75560905 ... 0.25729465 1.53460677 0.78389647]
 [0.49329477 1.86272174 1.21228185 ... 0.69664137 0.43474933 0.75788557]
 [0.82987473 1.96805983 1.13484256 ... 1.16320616 0.78220976 1.49526631]
 ...
 [1.20226185 0.23100344 1.78933247 ... 0.98533723 1.3757984  1.95134876]
 [0.60228763 1.04616538 0.88684185 ... 1.66299933 0.93898307 0.18343002]
 [1.98007067 0.69825227 0.33133584 ... 1.12119787 0.56698302 1.61931274]]


In [16]:
@jit(nopython=True)
def accelerated_calculation(data):
    result = np.zeros_like(data)
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            result[i, j] = data[i, j] ** 2 + data[i, j] ** 0.5
    return result

class Calculator:
    def __init__(self, data):
        self.data = data

    def complex_calculation(self):
        return accelerated_calculation(self.data)

if __name__ == "__main__":
    data = np.random.rand(1000, 1000)
    calc = Calculator(data)
    result = calc.complex_calculation()
    print(result)


[[0.35108772 1.0358058  0.50899431 ... 0.03080953 0.75513784 0.67405761]
 [0.83468077 0.39748036 1.09309834 ... 0.30329604 0.24848152 0.90484444]
 [0.3996413  0.64402225 0.27637836 ... 0.32156606 1.68078456 0.70090865]
 ...
 [1.72321202 0.299277   1.18207055 ... 1.55479121 0.25904014 1.02581539]
 [1.33791085 0.83892304 1.56279648 ... 0.39879325 0.64645942 0.23097269]
 [1.94571996 0.30554907 0.88471321 ... 0.5859012  1.78947215 1.21880108]]


In [30]:
react_table = np.array([[[0.01,2], [0.01,3], [0.01,4], [0.01,-4], [0.05,7], [0.00,0], [0.05,8], [0.00,0],[0.06,10],[0.00,0]],
                        [[0.05,5], [0.00,0], [0.00,0], [0.00, 0], [0.05,6], [0.00,0], [0.00,0], [0.00,0], [0.00,0],[0.00,0]],
                        [[0.27,-1], [0.27,-2], [0.27,-3], [0.27,-4], [0.27,-5], [0.27,-6], [0.27,-7], [0.27,-8], [0.27,-9], [0.27,-10]]])

print(react_table.shape)

(3, 10, 2)


In [31]:
print(np.random.choice(5))

3


In [37]:
react_table = np.array([[[0.01,2], [0.01,3], [0.01,4], [0.01,-4], [0.05,7], [0.00,0], [0.05,8], [0.00,0],[0.06,10],[0.00,0]],
                        [[0.05,5], [0.00,0], [0.00,0], [0.00, 0], [0.05,6], [0.00,0], [0.00,0], [0.00,0], [0.00,0],[0.00,0]],
                        [[0.27,-1], [0.27,-2], [0.27,-3], [0.27,-4], [0.27,-5], [0.27,-6], [0.27,-7], [0.27,-8], [0.27,-9], [0.27,-10]]])


@jit(nopython=True)
def reaction(parcel, film):
    # parcel(x, y, z, vel, cell, id) , film[in, filmType]
    choice = np.random.rand((parcel.shape[0], react_table.shape[1]))
    parcelGen = np.zeros(parcel.shape[0])
    for i in range(parcel.shape[0]):
        acceptList = np.zeros(react_table.shape[1])
        for j in range(film.shape[1]):
            react_rate = react_table[parcel[i], film[i, j], 0]
            if react_rate > choice[i, j]:
                acceptList[j] = True
            else:
                acceptList[j] = False
            react_choice = np.random.choice(np.sum(acceptList))
            film[i, react_choice] -= 0.01
            react_gen = react_table[parcel[i, -1], react_choice, 1]
            if react_gen > 0:
                film[i, react_gen] += 0.01
            else:
                parcelGen[i] = -react_gen
    return film, parcelGen



In [38]:
class unitTest:
    def __init__(self, parcel, film):
        self.parcel = parcel
        self.film = film
    
    def testReact(self):
        return reaction(self.parcel, self.film)
    


In [40]:
print(react_table.shape)

(3, 10, 2)


In [41]:
film = np.zeros((10, 10))
parcel = np.random.choice(3, size=10)
print(parcel)

[1 0 0 0 2 1 2 2 0 1]


In [43]:
test1 = unitTest(parcel, film)

print(test1.testReact())

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in method rand of numpy.random.mtrand.RandomState object at 0x00000242FF8CAC40>) found for signature:
 
 >>> rand(UniTuple(int64 x 2))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'rand': File: numba\cpython\randomimpl.py: Line 1882.
    With argument(s): '(UniTuple(int64 x 2))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<built-in method random of numpy.random.mtrand.RandomState object at 0x00000242FF8CAC40>) found for signature:
    
    >>> random(StarArgUniTuple(UniTuple(int64 x 2) x 1))
    
   There are 4 candidate implementations:
         - Of which 2 did not match due to:
         Overload in function 'random_impl0': File: numba\cpython\randomimpl.py: Line 241.
           With argument(s): '(StarArgUniTuple(UniTuple(int64 x 2) x 1))':
          Rejected as the implementation raised a specific error:
            TypingError: too many positional arguments
     raised from l:\program\Lib\site-packages\numba\core\typing\templates.py:784
         - Of which 2 did not match due to:
         Overload of function 'random': File: numba\cpython\randomimpl.py: Line 255.
           With argument(s): '(StarArgUniTuple(UniTuple(int64 x 2) x 1))':
          No match.
   
   During: resolving callee type: Function(<built-in method random of numpy.random.mtrand.RandomState object at 0x00000242FF8CAC40>)
   During: typing of call at l:\program\Lib\site-packages\numba\cpython\randomimpl.py (1892)
   
   
   File "..\..\program\Lib\site-packages\numba\cpython\randomimpl.py", line 1892:
           def rand_impl(*size):
               return np.random.random(size)
               ^

  raised from l:\program\Lib\site-packages\numba\core\typeinfer.py:1091

During: resolving callee type: Function(<built-in method rand of numpy.random.mtrand.RandomState object at 0x00000242FF8CAC40>)
During: typing of call at C:\Users\URCS049\AppData\Local\Temp\ipykernel_25320\219837210.py (9)


File "C:\Users\URCS049\AppData\Local\Temp\ipykernel_25320\219837210.py", line 9:
def reaction(parcel, film):
    <source elided>
    # parcel(x, y, z, vel, cell, id) , film[in, filmType]
    choice = np.random.rand((parcel.shape[0], react_table.shape[1]))
    ^


In [52]:
react_table = np.array([[[0.01,2], [0.01,3], [0.01,4], [0.01,-4], [0.05,7], [0.00,0], [0.05,8], [0.00,0],[0.06,10],[0.00,0]],
                        [[0.05,5], [0.00,0], [0.00,0], [0.00, 0], [0.05,6], [0.00,0], [0.00,0], [0.00,0], [0.00,0],[0.00,0]],
                        [[0.27,-1], [0.27,-2], [0.27,-3], [0.27,-4], [0.27,-5], [0.27,-6], [0.27,-7], [0.27,-8], [0.27,-9], [0.27,-10]]])


print(react_table[1, 5, 1])

0.0


In [54]:
film = np.zeros((10, 10))

print(film[1,1])

0.0


In [67]:
react_table = np.array([[[0.01,2], [0.01,3], [0.01,4], [0.01,-4], [0.05,7], [0.00,0], [0.05,8], [0.00,0],[0.06,10],[0.00,0]],
                        [[0.05,5], [0.00,0], [0.00,0], [0.00, 0], [0.05,6], [0.00,0], [0.00,0], [0.00,0], [0.00,0],[0.00,0]],
                        [[0.27,-1], [0.27,-2], [0.27,-3], [0.27,-4], [0.27,-5], [0.27,-6], [0.27,-7], [0.27,-8], [0.27,-9], [0.27,-10]]])


@jit(nopython=True)
def reaction(parcel, film):

    # parcel(x, y, z, vel, cell, id) , film[in, filmType]
    choice = np.random.rand(parcel.shape[0], react_table.shape[1])
    parcelGen = np.zeros(parcel.shape[0])
    for i in range(parcel.shape[0]):
        acceptList = np.zeros(react_table.shape[1], dtype=np.bool_)
        for j in range(film.shape[1]):
            react_rate = react_table[int(parcel[i]), int(film[i, j]), 0]
            if react_rate > choice[i, j]:
                acceptList[j] = True
            else:
                acceptList[j] = False
        react_choice = np.random.choice(int(np.sum(acceptList)))
        film[i, react_choice] -= 0.01
        react_gen = react_table[int(parcel[i]), react_choice, 1]
        if react_gen > 0:
            film[i, int(react_gen)] += 0.01
        else:
            parcelGen[i] = -react_gen
    return film, parcelGen

class unitTest:
    def __init__(self, parcel, film):
        self.parcel = parcel
        self.film = film
    
    def testReact(self):
        film, parcelGen =  reaction(self.parcel, self.film)
        return film, parcelGen
    

film = np.zeros((10, 10))
parcel = np.random.choice(3, size=10)

test1 = unitTest(parcel, film)

print(test1.testReact())

ValueError: empty range for randrange()

In [73]:
react_table = np.array([[[0.01, 2], [0.01, 3], [0.01, 4], [0.01, -4], [0.05, 7], [0.00, 0], [0.05, 8], [0.00, 0], [0.06, 10], [0.00, 0]],
                        [[0.05, 5], [0.00, 0], [0.00, 0], [0.00, 0], [0.05, 6], [0.00, 0], [0.00, 0], [0.00, 0], [0.00, 0], [0.00, 0]],
                        [[0.27, -1], [0.27, -2], [0.27, -3], [0.27, -4], [0.27, -5], [0.27, -6], [0.27, -7], [0.27, -8], [0.27, -9], [0.27, -10]]])

@jit(nopython=True)
def reaction(parcel, film):
    choice = np.random.rand(parcel.shape[0], react_table.shape[1])
    parcelGen = np.zeros(parcel.shape[0])
    reactList = np.zeros(parcel.shape[0])
    for i in range(parcel.shape[0]):
        acceptList = np.zeros(react_table.shape[1], dtype=np.bool_)
        
        for j in range(film.shape[1]):
            react_rate = react_table[parcel[i], j, 0]
            if react_rate > choice[i, j]:
                acceptList[j] = True
        
        # react_choice_indices = np.random.choice(int(np.sum(acceptList)))
        react_choice_indices = np.where(acceptList)[0]
        print(react_choice_indices)
        if react_choice_indices.size > 0:
            react_choice = np.random.choice(react_choice_indices)
            reactList[i] = react_choice
            film[i, react_choice] -= 0.01
            react_gen = react_table[parcel[i], react_choice, 1]
            if react_gen > 0:
                film[i, int(react_gen)] += 0.01
            else:
                parcelGen[i] = -react_gen
                
    return film, parcelGen, reactList

class UnitTest:
    def __init__(self, parcel, film):
        self.parcel = parcel
        self.film = film
    
    def testReact(self):
        film, parcelGen, reactList = reaction(self.parcel, self.film)
        return film, parcelGen, reactList

film = np.zeros((10, 10))
parcel = np.random.choice(3, size=10)

print(parcel)
# test1 = UnitTest(parcel, film)
# print(test1.testReact())

print(reaction(parcel, film))


[2 2 1 0 2 1 1 2 1 0]
[0 4]
[0 1]
[]
[]
[0 1 2]
[]
[]
[0 2 3 4 7]
[]
[]
(array([[-0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [-0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  , -0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  , -0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ]]), array([1., 1., 0., 0., 2., 0., 0., 4., 0., 0.]), array(

In [65]:
film = np.zeros((10, 10))
parcel = np.random.choice(3, size=10)
print(parcel)
test1 = UnitTest(parcel, film)
print(test1.testReact())


[0 2 2 1 1 1 1 2 2 2]
(array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01,  0.  ,  0.01,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.01,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.01,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  , -0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ]]), array([0., 9., 5., 0., 0., 0., 0., 6., 5., 4.]))
